imports:
    - { resource: tables.yml }
services:
    dmzx.youtubegallery.controller:
        class: dmzx\youtubegallery\controller\youtubegallery
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@user'
            - '@auth'
            - '@dbal.conn'
            - '@request'
            - '@pagination'
            - '@service_container'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%core.table_prefix%'
            - '%dmzx.youtubegallery.table.video%'
            - '%dmzx.youtubegallery.table.video_cat%'
            - '%dmzx.youtubegallery.table.video_cmnts%'
            - '@ext.manager'
    dmzx.youtubegallery.admin.controller:
        class: dmzx\youtubegallery\controller\admin_controller
        arguments:
            - '@config'
            - '@template'
            - '@log'
            - '@user'
            - '@dbal.conn'
            - '@request'
            - '@service_container'
            - '%dmzx.youtubegallery.table.video%'
            - '%dmzx.youtubegallery.table.video_cat%'
    dmzx.youtubegallery.ucp.controller:
        class: dmzx\youtubegallery\controller\ucp_controller
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@user'
            - '@auth'
            - '@pagination'
            - '@dbal.conn'
            - '@request'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%dmzx.youtubegallery.table.video%'
            - '%dmzx.youtubegallery.table.video_cat%'
    dmzx.youtubegallery.listener:
        class: dmzx\youtubegallery\event\listener
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@user'
            - '@auth'
            - '@dbal.conn'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%dmzx.youtubegallery.table.video%'
            - '%dmzx.youtubegallery.table.video_cat%'
            - '%dmzx.youtubegallery.table.video_cmnts%'
            - '@?phpbb.collapsiblecategories.operator'
            - '@?files.factory'
        tags:
            - { name: event.listener }
